[tool.poetry]
name = "versa"
version = "0.1.0"
description = "LAN chat app"
authors = ["Noid, Snipy"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
